server:
  port: 8080
  shutdown: "graceful"

# If you use a database then uncomment the `group:, readiness: and include: "db"` lines in the health probes and uncomment the datasource section
management:
  endpoint:
    health:
      show-details: "always"
      group:
        readiness:
          include: "db"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  config:
    import: "optional:configtree:/mnt/secrets/apim/,optional:configtree:/mnt/secrets/apim-sbox/"
  application:
    name: service-api-marketplace
  jpa:
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:marketplace}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    properties:
      charSet: UTF-8
    hikari:
      maximumPoolSize: 10
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
