package uk.gov.hmcts.cp.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.data.domain.Persistable;

import java.time.LocalDateTime;

/**
 * The reference is the primary key, so it is assigned by the application rather than
 * generated by the database. Persistable is what keeps that safe: without it Spring Data
 * sees an entity that already carries an id, treats it as detached and merges - which
 * would turn a reference collision into a silent overwrite of somebody else's row rather
 * than the failed insert it should be. It also spares every insert a select first.
 */
@Entity
@Table(name = "subscription_request")
@Getter
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
public class SubscriptionRequestEntity implements Persistable<String> {

    @Id
    private String reference;

    private String type;
    private String orgName;
    private String userName;
    private String userEmail;
    private String status;
    private LocalDateTime submittedAt;
    private String apiShortCode;
    private String api;
    private String environment;
    private String expectedVolume;
    private String useCase;
    private boolean oauth2Capable;
    private String declaration;

    @Transient
    @Builder.Default
    @EqualsAndHashCode.Exclude
    private boolean isNew = true;

    @Override
    public String getId() {
        return reference;
    }

    @PostLoad
    @PostPersist
    void markNotNew() {
        this.isNew = false;
    }
}
