package uk.gov.hmcts.cp.integration;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.test.context.ContextConfiguration;
import uk.gov.hmcts.cp.entity.SubscriptionRequestEntity;
import uk.gov.hmcts.cp.entity.OrganisationEntity;
import uk.gov.hmcts.cp.entity.UserEntity;
import uk.gov.hmcts.cp.repository.SubscriptionRepository;
import uk.gov.hmcts.cp.repository.OrganisationRepository;
import uk.gov.hmcts.cp.repository.UserRepository;

import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest
@ContextConfiguration(initializers = TestContainersInitialise.class)
class RepositoryIntegrationTest {

    @Autowired
    private OrganisationRepository organisationRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private SubscriptionRepository subscriptionRepository;

    @Test
    void getting_org_by_id_should_return_seeded_api_marketplace_org() {
        Optional<OrganisationEntity> org = organisationRepository.findById(1);

        assertThat(org).isPresent();
        assertThat(org.get().getName()).isEqualTo("Api Marketplace");
    }

    @Test
    void getting_user_by_email_should_return_seeded_colin_greenwood() {
        Optional<UserEntity> user = userRepository.findByEmail("colin.greenwood@hmcts.net");

        assertThat(user).isPresent();
        assertThat(user.get().getFirstName()).isEqualTo("Colin");
        assertThat(user.get().getLastName()).isEqualTo("Greenwood");
        assertThat(user.get().getStatus()).isEqualTo("ACTIVE");
        assertThat(user.get().getOrganisation().getName()).isEqualTo("Api Marketplace");
    }

    @Test
    void saving_a_subscription_request_should_persist_to_database() {
        // The id is generated by @GeneratedValue, so it is read back from the saved entity.
        // Assigning one here would make Spring Data treat this as a detached entity and merge.
        SubscriptionRequestEntity request = SubscriptionRequestEntity.builder()
            .type("SUBSCRIPTION")
            .reference("AR-2026-TEST01")
            .orgName("Api Marketplace")
            .userName("Colin Greenwood")
            .userEmail("alan@example.com")
            .status("PENDING")
            .submittedAt(LocalDateTime.now())
            .build();

        SubscriptionRequestEntity saved = subscriptionRepository.save(request);

        assertThat(saved.getId()).isNotNull();
        assertThat(subscriptionRepository.existsById(saved.getId())).isTrue();
    }

    @Test
    void getting_a_saved_subscription_request_should_return_correct_data() {
        SubscriptionRequestEntity saved = subscriptionRepository.save(
            SubscriptionRequestEntity.builder()
                .type("SUBSCRIPTION")
                .reference("AR-2026-TEST02")
                .orgName("Api Marketplace")
                .userName("Colin Greenwood")
                .userEmail("joe.bloggs@example.com")
                .status("PENDING")
                .submittedAt(LocalDateTime.of(2026, 1, 15, 9, 0))
                .build()
        );

        Optional<SubscriptionRequestEntity> found = subscriptionRepository.findById(saved.getId());

        assertThat(found).isPresent();
        assertThat(found.get().getType()).isEqualTo("SUBSCRIPTION");
        assertThat(found.get().getReference()).isEqualTo("AR-2026-TEST02");
        assertThat(found.get().getOrgName()).isEqualTo("Api Marketplace");
        assertThat(found.get().getUserEmail()).isEqualTo("joe.bloggs@example.com");
        assertThat(found.get().getStatus()).isEqualTo("PENDING");
    }

    @Test
    void getting_a_subscription_request_by_reference_should_return_correct_data() {
        subscriptionRepository.save(
            SubscriptionRequestEntity.builder()
                .type("SUBSCRIPTION")
                .reference("AR-2026-TEST03")
                .orgName("Api Marketplace")
                .userName("Colin Greenwood")
                .userEmail("by.reference@example.com")
                .status("PENDING")
                .submittedAt(LocalDateTime.of(2026, 2, 3, 11, 30))
                .build()
        );

        Optional<SubscriptionRequestEntity> found = subscriptionRepository.findByReference("AR-2026-TEST03");

        assertThat(found).isPresent();
        assertThat(found.get().getUserEmail()).isEqualTo("by.reference@example.com");
    }

    @Test
    void getting_a_subscription_request_by_unknown_reference_should_return_empty() {
        assertThat(subscriptionRepository.findByReference("AR-2026-NOSUCH")).isEmpty();
    }

    @Test
    void saving_a_reference_shaped_like_a_uuid_should_be_rejected_by_the_database() {
        // The reference is the only identifier the API exposes for a request, so writing
        // a primary key into the column - the mistake that would put UUIDs back in front
        // of callers - is refused rather than stored.
        SubscriptionRequestEntity request = SubscriptionRequestEntity.builder()
            .type("SUBSCRIPTION")
            .reference(UUID.randomUUID().toString())
            .orgName("Api Marketplace")
            .userName("Colin Greenwood")
            .userEmail("uuid.reference@example.com")
            .status("PENDING")
            .submittedAt(LocalDateTime.now())
            .build();

        assertThatThrownBy(() -> subscriptionRepository.saveAndFlush(request))
            .isInstanceOf(DataIntegrityViolationException.class);
    }
}
