package uk.gov.hmcts.cp.integration;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ContextConfiguration;
import uk.gov.hmcts.cp.entity.SubscriptionRequestEntity;
import uk.gov.hmcts.cp.entity.OrganisationEntity;
import uk.gov.hmcts.cp.entity.UserEntity;
import uk.gov.hmcts.cp.repository.SubscriptionRepository;
import uk.gov.hmcts.cp.repository.OrganisationRepository;
import uk.gov.hmcts.cp.repository.UserRepository;

import java.time.LocalDateTime;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest
@ContextConfiguration(initializers = TestContainersInitialise.class)
class RepositoryIntegrationTest {

    @Autowired
    private OrganisationRepository organisationRepository;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private SubscriptionRepository subscriptionRepository;

    @Test
    void getting_org_by_id_should_return_seeded_api_marketplace_org() {
        Optional<OrganisationEntity> org = organisationRepository.findById(1);

        assertThat(org).isPresent();
        assertThat(org.get().getName()).isEqualTo("Api Marketplace");
    }

    @Test
    void getting_user_by_email_should_return_seeded_colin_greenwood() {
        Optional<UserEntity> user = userRepository.findByEmail("colin.greenwood@hmcts.net");

        assertThat(user).isPresent();
        assertThat(user.get().getFirstName()).isEqualTo("Colin");
        assertThat(user.get().getLastName()).isEqualTo("Greenwood");
        assertThat(user.get().getStatus()).isEqualTo("ACTIVE");
        assertThat(user.get().getOrganisation().getName()).isEqualTo("Api Marketplace");
    }

    @Test
    void saving_a_marketplace_request_should_persist_to_database() {
        // The id is generated by @GeneratedValue, so it is read back from the saved entity.
        // Assigning one here would make Spring Data treat this as a detached entity and merge.
        SubscriptionRequestEntity request = SubscriptionRequestEntity.builder()
            .type("SUBSCRIPTION")
            .orgName("Api Marketplace")
            .userName("Colin Greenwood")
            .userEmail("alan@example.com")
            .status("PENDING")
            .submittedAt(LocalDateTime.now())
            .build();

        SubscriptionRequestEntity saved = subscriptionRepository.save(request);

        assertThat(saved.getId()).isNotNull();
        assertThat(subscriptionRepository.existsById(saved.getId())).isTrue();
    }

    @Test
    void getting_a_saved_marketplace_request_should_return_correct_data() {
        SubscriptionRequestEntity saved = subscriptionRepository.save(
            SubscriptionRequestEntity.builder()
                .type("SUBSCRIPTION")
                .orgName("Api Marketplace")
                .userName("Colin Greenwood")
                .userEmail("joe.bloggs@example.com")
                .status("PENDING")
                .submittedAt(LocalDateTime.of(2026, 1, 15, 9, 0))
                .build()
        );

        Optional<SubscriptionRequestEntity> found = subscriptionRepository.findById(saved.getId());

        assertThat(found).isPresent();
        assertThat(found.get().getType()).isEqualTo("SUBSCRIPTION");
        assertThat(found.get().getOrgName()).isEqualTo("Api Marketplace");
        assertThat(found.get().getUserEmail()).isEqualTo("joe.bloggs@example.com");
        assertThat(found.get().getStatus()).isEqualTo("PENDING");
    }
}
